<?php
/**
 * CloudScale shared Telegram notification helper.
 *
 * Credentials are stored under shared wp_options keys so any CloudScale plugin
 * that includes this file can send and configure Telegram without duplicating logic.
 *
 * DO NOT EDIT THIS FILE in individual plugin directories.
 * Edit shared-admin-ui/class-cloudscale-telegram.php and run sync-admin-css.sh.
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

if ( class_exists( 'CloudScale_Telegram' ) ) {
	return;
}

// phpcs:disable WordPress.NamingConventions.PrefixAllGlobals.NonPrefixedClassFound -- shared cross-plugin utility; CloudScale IS the brand prefix
class CloudScale_Telegram {
// phpcs:enable WordPress.NamingConventions.PrefixAllGlobals.NonPrefixedClassFound

	/**
	 * Option names, and why there are two sets of them.
	 *
	 * WordPress.org named `cloudscale_telegram_bot_token` and `cloudscale_telegram_chat_id` in
	 * its 18 Aug 2026 review as options not carrying the plugin's declared prefix, so the live
	 * names moved to `csdt_`. These four options are DELIBERATELY shared by all five plugins —
	 * one Telegram configuration for the whole suite, and only one copy of this class ever loads
	 * (see the class_exists() guard) — so they cannot be prefixed per-plugin without splitting
	 * one config into five.
	 *
	 * Renaming a live option is the dangerous part: the token, chat id and mute switch are what
	 * make alerting work at all, and the five plugins do not deploy at the same instant. So every
	 * read falls back to the legacy name and every write updates BOTH, which means an install
	 * running any mix of old and new copies keeps working in either direction.
	 *
	 * The legacy writes can be dropped once all five plugins have shipped with the new names —
	 * not before. `dr-restore.sh` also writes the legacy mute key from outside PHP, which is the
	 * specific reason is_muted() honours either name rather than preferring one.
	 */
	const OPTION_TOKEN   = 'csdt_telegram_bot_token'; // pragma:allow-secret
	const OPTION_CHAT_ID = 'csdt_telegram_chat_id';

	const LEGACY_TOKEN   = 'cloudscale_telegram_bot_token'; // pragma:allow-secret
	const LEGACY_CHAT_ID = 'cloudscale_telegram_chat_id';
	const LEGACY_MUTED   = 'cloudscale_alerts_muted';
	const LEGACY_RATE    = 'cloudscale_alert_rate';

	/**
	 * Reads the new option name, falling back to the legacy one while both may exist.
	 *
	 * An option that is present but empty counts as absent here: a half-migrated install can
	 * hold an empty new-style row alongside a populated legacy one, and preferring the empty
	 * value would disarm alerting silently — the failure mode this whole class exists to avoid.
	 *
	 * @param string $new    New option name.
	 * @param string $legacy Legacy option name.
	 * @param mixed  $fallback Returned when neither is set.
	 * @return mixed
	 */
	private static function opt_read( string $new, string $legacy, $fallback = '' ) {
		$value = get_option( $new, null );
		if ( null !== $value && '' !== $value && array() !== $value ) {
			return $value;
		}
		return get_option( $legacy, $fallback );
	}

	/**
	 * Writes both the new and the legacy option name.
	 *
	 * @param string $new      New option name.
	 * @param string $legacy   Legacy option name.
	 * @param mixed  $value    Value to store.
	 * @param bool   $autoload Autoload flag, passed through to both rows.
	 */
	private static function opt_write( string $new, string $legacy, $value, bool $autoload = false ): void {
		update_option( $new, $value, $autoload );
		update_option( $legacy, $value, $autoload );
	}

	/**
	 * One switch that silences every alert from every plugin on this install.
	 *
	 * Until this existed there was no way to mute a host. send() gated only on the
	 * token and chat id being present, and each call site checked its own feature
	 * toggle — so `csdt_notify_telegram_enabled` silenced the paths that happened to
	 * consult it and nothing else. CSDT_Test_Accounts::send_security_alert() was one
	 * of the ones that did not.
	 *
	 * That is a problem specifically for a COPY. A restored DR or QA instance keeps
	 * production's site URL, database and bot token, so it pages the owner as though
	 * it were production, and there was nothing to flip to stop it: the only lever
	 * was clearing the shared token, which also disarms the real site. On 2026-08-07
	 * a QA copy on the DR host emitted hundreds of "elevated test session minted"
	 * alerts while a Playwright suite ran against it, and no setting anywhere could
	 * shut it up.
	 *
	 * So this is deliberately the FIRST thing send() checks, and it is checked here
	 * rather than at the call sites, because the point is that no future call site
	 * can forget it. dr-restore.sh sets it on every copy it builds.
	 */
	const OPTION_MUTED = 'csdt_alerts_muted';

	/**
	 * Is this install muted? True on restored copies (see OPTION_MUTED).
	 *
	 * EITHER name muting is enough. dr-restore.sh writes the legacy key directly, and a copy
	 * that believes it is production is exactly the case where guessing wrong pages a human at
	 * 3am — so this errs toward silence rather than toward preferring the new name.
	 */
	public static function is_muted(): bool {
		return '1' === (string) get_option( self::OPTION_MUTED, '' )
			|| '1' === (string) get_option( self::LEGACY_MUTED, '' );
	}

	/**
	 * The rate ledger: what has actually been sent, and what has been held back.
	 *
	 * AN OPTION, NOT A TRANSIENT, and that is the whole reason this exists centrally.
	 *
	 * Every throttle in these five plugins was a transient with a 6-hour expiry, and every one of
	 * them read as correct. This install runs a persistent Redis object cache, so transients live in
	 * Redis while options live in MariaDB — and every deploy of any of the five runs `wp cache flush`
	 * and reloads PHP-FPM. That deleted every quiet window: the next failure reported an ongoing
	 * incident as new. Several deploys a day, several identical alerts a day, from throttles that
	 * passed their own tests because a test never flushes a cache it is not using. Reported
	 * 2026-08-13 as "I don't want to get these spammed at me".
	 *
	 * WHY IT IS HERE RATHER THAN AT THE CALL SITES, which is the same argument as OPTION_MUTED one
	 * constant above: there are 123 send() call sites across the five plugins. Eight of them had a
	 * throttle; the rest could flood freely, and any new one starts with no throttle at all. A
	 * guarantee that has to be remembered 123 times is not a guarantee.
	 */
	const OPTION_RATE = 'csdt_alert_rate';

	/**
	 * How long a REPEAT of the same alert stays quiet, by level.
	 *
	 * Keyed on a signature that ignores the numbers inside the message (see rate_signature), because
	 * "cURL error 28: timed out after 90002ms" and "...after 90003ms" are the same news. A critical
	 * gets the shortest window: it is the level that describes something still on fire, where a
	 * second message an hour later is information rather than noise.
	 */
	const DUP_WINDOW = [
		'critical' => 3600,        // 1h
		'error'    => 21600,      // 6h
		'warning'  => 21600,      // 6h
		'info'     => 86400,      // 24h
	];

	/**
	 * The hard ceiling, whatever the callers do.
	 *
	 * Duplicate suppression alone cannot bound the volume: fifty DIFFERENT alerts in a minute is
	 * still a phone nobody can read, and a burst of distinct-but-related messages is exactly what a
	 * failing batch job produces. So the total is capped as well, and the cap is not per-level — the
	 * reader's attention is one pool.
	 *
	 * 6 an hour and 24 a day are chosen to be higher than any real incident needs and far below the
	 * volume that makes alerts unreadable. Held messages are counted and reported on the next one
	 * that goes out (see rate_release), so a cap that bites is visible rather than a silence.
	 */
	const MAX_PER_HOUR = 6;
	const MAX_PER_DAY  = 24;

	/*
	 * There is deliberately NO bypass parameter. Every alert that goes through send() is capped,
	 * including criticals — a level that could opt out would become the level everything uses. The
	 * one message that must always arrive, the settings page's "send test message", posts to
	 * Telegram directly (see register_ajax) and never reaches this gate, so the button still tells
	 * the truth about whether alerts work.
	 */

	/**
	 * The signature two alerts share when they are the same news.
	 *
	 * Numbers are dropped, not kept: timings, byte counts, IP addresses, streak counters and dates
	 * are what differ between repeats of one incident, and keeping them would make every repeat
	 * unique — a throttle that never fires. The first 160 characters are enough to tell one alert
	 * apart from another while ignoring the detail that accumulates further down (the host block,
	 * the local time, the request path).
	 *
	 * @param string $text   Message body.
	 * @param string $source Sending plugin/feature.
	 * @param string $level  Alert level.
	 * @return string 32-char hex signature.
	 */
	private static function rate_signature( string $text, string $source, string $level ): string {
		$key = strtolower( $source . '|' . $level . '|' . substr( $text, 0, 160 ) );
		$key = preg_replace( '/\d+/', '#', $key );
		$key = preg_replace( '/\s+/', ' ', (string) $key );
		return md5( (string) $key );
	}

	/**
	 * May this alert go out now? Records the decision either way.
	 *
	 * Returns the message to send — the body plus, when messages were held back since the last one
	 * delivered, a line saying how many — or null when it must stay quiet.
	 *
	 * @param string $text   Message body.
	 * @param string $source Sending plugin/feature.
	 * @param string $level  Alert level.
	 * @return string|null
	 */
	private static function rate_gate( string $text, string $source, string $level ): ?string {
		$now  = time();
		$led  = self::opt_read( self::OPTION_RATE, self::LEGACY_RATE, [] );
		if ( ! is_array( $led ) ) {
			$led = [];
		}
		$sent = array_values( array_filter(
			array_map( 'intval', (array) ( $led['sent'] ?? [] ) ),
			static function ( $t ) use ( $now ) {
				return $t > 0 && ( $now - $t ) < DAY_IN_SECONDS;
			}
		) );
		$sigs = is_array( $led['sigs'] ?? null ) ? $led['sigs'] : [];
		$held = (int) ( $led['held'] ?? 0 );
		$dups = (int) ( $led['dups'] ?? 0 );

		$sig    = self::rate_signature( $text, $source, $level );
		$window = self::DUP_WINDOW[ $level ] ?? self::DUP_WINDOW['warning'];
		$last   = (int) ( $sigs[ $sig ] ?? 0 );

		$blocked = '';
		// A clock that has gone backwards must not mute anything until it catches up.
		if ( $last > 0 && $last <= $now && ( $now - $last ) < $window ) {
			$blocked = 'dup';
		} else {
			$hour = 0;
			foreach ( $sent as $t ) {
				if ( ( $now - $t ) < HOUR_IN_SECONDS ) {
					++$hour;
				}
			}
			if ( $hour >= self::MAX_PER_HOUR || count( $sent ) >= self::MAX_PER_DAY ) {
				$blocked = 'cap';
			}
		}

		if ( '' !== $blocked ) {
			$led['held'] = $held + 1;
			$led['dups'] = $dups + ( 'dup' === $blocked ? 1 : 0 );
			$led['sent'] = $sent;
			$led['sigs'] = $sigs;
			self::opt_write( self::OPTION_RATE, self::LEGACY_RATE, $led, false );
			return null;
		}

		// Going out: stamp the signature, drop signatures older than a day so the ledger cannot
		// grow without bound, and reset the held counters now that they are about to be reported.
		$sigs[ $sig ] = $now;
		foreach ( $sigs as $k => $t ) {
			if ( ( $now - (int) $t ) > DAY_IN_SECONDS ) {
				unset( $sigs[ $k ] );
			}
		}
		$sent[] = $now;
		self::opt_write(
			self::OPTION_RATE,
			self::LEGACY_RATE,
			[ 'sent' => $sent, 'sigs' => $sigs, 'held' => 0, 'dups' => 0 ],
			false
		);

		if ( $held > 0 ) {
			// Said on the alert that DOES go out, rather than as a message of its own: a digest that
			// is itself an alert would be one more thing arriving on the phone.
			$text .= "\n\n" . sprintf(
				'(%d further alert%s held back since the last one, %d of them repeats of something already reported. Alerts are capped at %d an hour.)',
				$held,
				1 === $held ? ' was' : 's were',
				$dups,
				self::MAX_PER_HOUR
			);
		}
		return $text;
	}

	public static function is_configured(): bool {
		return ! empty( self::opt_read( self::OPTION_TOKEN, self::LEGACY_TOKEN ) )
			&& ! empty( self::opt_read( self::OPTION_CHAT_ID, self::LEGACY_CHAT_ID ) );
	}

	/**
	 * Build the alert prefix line: "{emoji} Domain : Source\nLEVEL\n\n"
	 *
	 * The marker and the LEVEL word beside it must never disagree, and they did.
	 * The map held only info/warning/error/critical and an unrecognised level fell
	 * back to info, so the one call site that says 'high' — the front-end asset
	 * monitor — shipped real failures as "✅ <site name> ... HIGH". A green
	 * tick over a broken asset is the most misleading thing an alert can look like
	 * on a phone: it is read before the words are.
	 *
	 * So the severity vocabularies that actually reach here are mapped onto the four
	 * markers, and anything still unrecognised gets a warning. ✅ is reserved for
	 * levels that genuinely mean "nothing is wrong" and cannot be reached by
	 * accident or by a typo.
	 *
	 * @param string $source  Human-readable plugin/feature name, e.g. "Backup and Restore".
	 * @param string $level   One of: info, warning, error, critical (aliases: success, notice, low, medium, high, urgent, alert, fatal).
	 */
	private static function alert_prefix( string $source, string $level ): string {
		$host   = (string) ( wp_parse_url( home_url(), PHP_URL_HOST ) ?: '' );
		$domain = implode( '.', array_map( 'ucfirst', explode( '.', strtolower( $host ) ) ) );

		$emojis = [
			'info'     => "\u{2705}",
			'warning'  => "\u{26A0}\u{FE0F}",
			'error'    => "\u{274C}",
			'critical' => "\u{1F6A8}",
		];
		// Words that arrived from another severity vocabulary — a scanner's
		// low/medium/high, a caller's "urgent" — resolve to one of the four rather
		// than falling through to the tick.
		$aliases = [
			'success' => 'info',
			'notice'  => 'info',
			'low'     => 'warning',
			'medium'  => 'warning',
			'high'    => 'error',
			'urgent'  => 'critical',
			'alert'   => 'critical',
			'fatal'   => 'critical',
		];
		$key = strtolower( trim( $level ) );
		if ( '' === $key ) {
			$key = 'info';
		}
		$key   = $aliases[ $key ] ?? $key;
		$emoji = $emojis[ $key ] ?? $emojis['warning'];
		// The caller's own word is what prints: "HIGH" carries more than "ERROR"
		// would, and rewriting it would hide which vocabulary the alert came from.
		// Only the marker is derived.
		$label = strtoupper( trim( $level ) ?: 'INFO' );

		$header = $source ? $domain . ' : ' . $source : $domain;
		return $emoji . ' ' . $header . "\n" . $label . "\n\n";
	}

	/**
	 * Identify the machine that produced this alert.
	 *
	 * Stamped here rather than at the ~110 call sites across five plugins, for
	 * the same reason the mute check and the timestamp live here: a new call
	 * site cannot ship without it.
	 *
	 * The domain in alert_prefix() cannot do this job. As OPTION_MUTED's
	 * docblock records, a restored DR or QA copy keeps production's site URL,
	 * database and bot token, so every clone claims to be production. The
	 * machine hostname is the field that actually differs, which is why it
	 * leads. On 2026-08-07 hundreds of alerts from a QA copy on the DR host
	 * were indistinguishable from production's, and the only address in them
	 * was 172.20.0.1 — that copy's Docker gateway. That is why an unroutable
	 * address is now labelled rather than presented as the visitor's IP.
	 */
	private static function alert_origin(): string {
		$host = gethostname();
		if ( ! is_string( $host ) || '' === $host ) {
			$host = 'unknown-host';
		}

		$server_ip = isset( $_SERVER['SERVER_ADDR'] )
			? sanitize_text_field( wp_unslash( $_SERVER['SERVER_ADDR'] ) )
			: '';
		if ( ! filter_var( $server_ip, FILTER_VALIDATE_IP ) ) {
			$server_ip = '';
		}

		$lines   = array();
		$lines[] = 'Host: ' . $host . ( '' !== $server_ip ? ' (' . $server_ip . ')' : '' );
		$lines[] = 'From: ' . self::trigger_source();

		$account = self::acting_account();
		if ( '' !== $account ) {
			$lines[] = 'Account: ' . $account;
		}

		$method = isset( $_SERVER['REQUEST_METHOD'] )
			? sanitize_text_field( wp_unslash( $_SERVER['REQUEST_METHOD'] ) )
			: '';
		$uri = isset( $_SERVER['REQUEST_URI'] )
			? sanitize_text_field( wp_unslash( $_SERVER['REQUEST_URI'] ) )
			: '';
		if ( '' !== $method || '' !== $uri ) {
			// Long query strings would push the body toward Telegram's 4096-char
			// limit and truncate the alert itself, which matters more than the tail
			// of a URL.
			$request = trim( $method . ' ' . $uri );
			if ( strlen( $request ) > 120 ) {
				$request = substr( $request, 0, 117 ) . '...';
			}
			$lines[] = 'Request: ' . $request;
		}

		return "\n" . implode( "\n", $lines );
	}

	/**
	 * The WordPress account attached to this request, when there is one.
	 *
	 * "From: 41.198.157.47" alone reads as an unknown attacker even when the request carried a
	 * valid, currently-authenticated admin session — the one piece of context that actually
	 * answers "is this me" was missing from every alert. Added rather than assumed: wp-cron and
	 * WP-CLI genuinely have no session, and a request whose auth cookie has not been processed
	 * yet at the point send() runs gets no line rather than a guessed one.
	 *
	 * @return string The user_login, or '' when no session is attached to this request.
	 */
	private static function acting_account(): string {
		if ( ! function_exists( 'get_current_user_id' ) || ! function_exists( 'wp_get_current_user' ) ) {
			return '';
		}
		if ( 0 === (int) get_current_user_id() ) {
			return '';
		}
		$user = wp_get_current_user();
		return ( $user && $user->exists() ) ? sanitize_text_field( $user->user_login ) : '';
	}

	/**
	 * What triggered this alert: a request with a client IP, or a background
	 * context that genuinely has no client. Never invent an address for the
	 * latter — a wrong IP is worse than an admitted absence.
	 */
	private static function trigger_source(): string {
		if ( defined( 'WP_CLI' ) && WP_CLI ) {
			return 'WP-CLI (no client IP)';
		}
		if ( function_exists( 'wp_doing_cron' ) && wp_doing_cron() ) {
			return 'wp-cron (no client IP)';
		}

		// Prefer the validated helper: it honours HTTP_CF_CONNECTING_IP and
		// X-Forwarded-For only when the immediate peer is a trusted proxy, so an
		// attacker cannot dictate what this alert reports. It lives in Cyber
		// DevTools, hence the guard — this file ships in five plugins.
		//
		// BOTH class names are tried because Cyber DevTools renamed this class to CSDT_DevTools
		// for WordPress.org's prefixing rule, and a shared file cannot know which version of
		// that plugin is installed beside it. Getting this wrong is quiet rather than loud: the
		// fallback below is REMOTE_ADDR, which on this install is the container gateway, so the
		// alert would name the proxy instead of the attacker and still look plausible.
		$ip = '';
		foreach ( array( 'CSDT_DevTools', 'CloudScale_DevTools' ) as $devtools_class ) {
			if ( is_callable( array( $devtools_class, 'get_client_ip' ) ) ) {
				$ip = (string) call_user_func( array( $devtools_class, 'get_client_ip' ) );
				break;
			}
		}
		if ( '' === $ip && isset( $_SERVER['REMOTE_ADDR'] ) ) {
			$ip = sanitize_text_field( wp_unslash( $_SERVER['REMOTE_ADDR'] ) );
		}
		if ( ! filter_var( $ip, FILTER_VALIDATE_IP ) ) {
			return 'no client IP (background context)';
		}

		// A private or loopback address is the container gateway or a reverse
		// proxy, not the visitor. Label it so it is never read as the origin.
		$is_public = (bool) filter_var(
			$ip,
			FILTER_VALIDATE_IP,
			FILTER_FLAG_NO_PRIV_RANGE | FILTER_FLAG_NO_RES_RANGE
		);

		return $is_public
			? $ip
			: $ip . ' (private address - proxy/container gateway, not the visitor)';
	}

	/**
	 * The site's own clock, with the zone named: "2026-08-05 07:02:11 SAST".
	 *
	 * wp_date() applies the timezone configured in Settings → General, and the T
	 * format character supplies the abbreviation, so the reader never has to do
	 * arithmetic or guess which zone a bare time is in.
	 *
	 * @param int|null $ts Unix timestamp; current time when null.
	 */
	public static function local_time( ?int $ts = null ): string {
		$ts   = $ts ?? time();
		$when = wp_date( 'Y-m-d H:i:s', $ts );
		// wp_date() returns false if the timezone is unusable; never let a broken
		// setting cost us the whole alert.
		if ( ! is_string( $when ) || '' === $when ) {
			return gmdate( 'Y-m-d H:i:s', $ts ) . ' UTC';
		}
		return $when . ' ' . self::tz_label( $ts );
	}

	/**
	 * The timezone label to print: a real zone abbreviation when there is one.
	 *
	 * Settings → General accepts either a named zone (Africa/Johannesburg, which
	 * makes wp_date('T') produce SAST) or a bare UTC offset. With a bare offset there
	 * IS no zone name, and wp_date('T') answers "GMT+0200" — which reads as a GMT
	 * time to anyone scanning an alert, and GMT is not what the clock is showing.
	 *
	 * An offset-shaped label is therefore resolved to a zone abbreviation, via PHP's
	 * own offset→zone table, rather than printed as "+02:00": alerts should name the
	 * clock they are quoting, and a bare offset makes the reader do the work. Several
	 * zones share an offset and PHP returns the canonical one, so the abbreviation is
	 * right for the offset even where the zone id is not the site's own — which is why
	 * the *offset* is what gets resolved and never invented from anything else. Set a
	 * named zone in Settings → General and this returns its own abbreviation directly.
	 *
	 * @param int|null $ts Timestamp the label applies to (DST-dependent zones).
	 */
	public static function tz_label( ?int $ts = null ): string {
		$ts   = $ts ?? time();
		$abbr = (string) wp_date( 'T', $ts );
		if ( preg_match( '/^(?:GMT|UTC)?\s*([+-])(\d{1,2}):?(\d{2})?$/', $abbr, $m ) ) {
			$seconds = ( (int) $m[2] * 3600 ) + ( (int) ( $m[3] ?? 0 ) * 60 );
			if ( '-' === $m[1] ) {
				$seconds = -$seconds;
			}
			// The candidate zone's offset AT THIS INSTANT must equal the offset we are
			// labelling. Without that check, +02:00 resolved to a zone whose
			// abbreviation was EEST — a real name for a clock that is +03:00 in
			// August, printed next to a time that is +02:00. A label contradicting
			// the timestamp it labels is worse than a bare offset.
			$moment     = new DateTime( '@' . $ts );
			$candidates = array();
			foreach ( array( 0, 1 ) as $dst ) {
				$guess = timezone_name_from_abbr( '', $seconds, $dst );
				if ( is_string( $guess ) && '' !== $guess ) {
					$candidates[] = $guess;
				}
			}
			// Nothing from the abbreviation table fits, so ask the zone list directly.
			$candidates = array_merge( $candidates, timezone_identifiers_list() );
			foreach ( $candidates as $zone ) {
				try {
					$tz = new DateTimeZone( $zone );
				} catch ( \Exception $e ) {
					unset( $e );
					continue;
				}
				if ( $tz->getOffset( $moment ) !== $seconds ) {
					continue;
				}
				$named = $moment->setTimezone( $tz )->format( 'T' );
				// A zone whose own label is offset-shaped puts us back where we
				// started, so keep looking.
				if ( is_string( $named ) && '' !== $named && ! preg_match( '/^(?:GMT|UTC)?[+-]/', $named ) ) {
					return $named;
				}
			}
			// Last resort: the offset, never "GMT+0200".
			return $m[1] . str_pad( $m[2], 2, '0', STR_PAD_LEFT ) . ':' . ( $m[3] ?? '00' );
		}
		return '' !== $abbr ? $abbr : 'UTC';
	}

	/**
	 * Rewrite UTC timestamps inside an alert body into the site's local zone.
	 *
	 * Alerts quote times from places that are UTC by construction — PHP's error log
	 * writes "[04-Aug-2026 20:40:15 UTC]", and several of our own messages used
	 * gmdate(). An alert that says one thing in the footer and another in the body
	 * makes the reader do timezone arithmetic at exactly the moment they can least
	 * afford to, so both are converted to the same clock.
	 *
	 * Only strings explicitly labelled UTC are touched. A time with no zone on it
	 * is left alone rather than guessed at.
	 */
	private static function localise_utc_stamps( string $text ): string {
		// PHP error-log prefix: [04-Aug-2026 20:40:15 UTC] — and GMT, which is what
		// PHP actually emits when date.timezone is UTC. Matching only "UTC" is why
		// alerts kept showing a GMT stamp after every other clock had been localised:
		// the copy was correct everywhere we controlled and wrong on the one line we
		// were quoting verbatim out of the log.
		$text = (string) preg_replace_callback(
			'/\[(\d{2}-[A-Za-z]{3}-\d{4} \d{2}:\d{2}:\d{2}) (?:UTC|GMT)\]/',
			static function ( array $m ): string {
				$ts = strtotime( $m[1] . ' UTC' );
				return false === $ts ? $m[0] : '[' . self::local_time( $ts ) . ']';
			},
			$text
		);
		// ISO-ish: 2026-08-05 02:30:01 UTC
		$text = (string) preg_replace_callback(
			'/(\d{4}-\d{2}-\d{2}[ T]\d{2}:\d{2}:\d{2})Z?\s+(?:UTC|GMT)\b/',
			static function ( array $m ): string {
				$ts = strtotime( str_replace( 'T', ' ', $m[1] ) . ' UTC' );
				return false === $ts ? $m[0] : self::local_time( $ts );
			},
			$text
		);
		return $text;
	}

	/**
	 * Send a Telegram message. Returns true on success.
	 *
	 * @param string $text    Message body.
	 * @param string $source  Plugin/feature name shown in the header (e.g. "Backup and Restore").
	 * @param string $level   Alert level: info, warning, error, critical.
	 */
	public static function send( string $text, string $source = '', string $level = 'info' ): bool {
		// Before anything else, and before any call site's own toggle: a muted install
		// sends nothing at all. See OPTION_MUTED for why this belongs here and not at
		// the ~20 call sites.
		if ( self::is_muted() ) {
			return false;
		}

		$token   = trim( (string) self::opt_read( self::OPTION_TOKEN, self::LEGACY_TOKEN, '' ) );
		$chat_id = trim( (string) self::opt_read( self::OPTION_CHAT_ID, self::LEGACY_CHAT_ID, '' ) );
		if ( ! $token || ! $chat_id ) {
			return false;
		}

		// The rate ceiling, after the credential check so a misconfigured install does not burn its
		// hourly allowance on messages that were never going to be sent, and before composing the
		// message so a held alert costs nothing. See OPTION_RATE for why this is here and not at the
		// 123 call sites.
		$gated = self::rate_gate( $text, $source, $level );
		if ( null === $gated ) {
			return false;
		}
		$text = $gated;

		// Local time and originating host on EVERY alert, stamped here rather than
		// at the call sites so a new alert cannot ship without either. Times quoted
		// inside the body are converted to the same clock — see
		// localise_utc_stamps(); see alert_origin() for why the site domain alone
		// cannot attribute a clone.
		// Order matters: the origin block goes BEFORE the timestamp because
		// check-telegram-local-time.php asserts the message ENDS with a zone-named
		// local time. That invariant is worth keeping — it is what proves no alert
		// ever ships without a readable clock — so attribution slots in above it
		// rather than the gate being relaxed to accommodate this.
		$full = self::alert_prefix( $source, $level )
			. self::localise_utc_stamps( $text )
			. "\n" . self::alert_origin()
			. "\n\n" . self::local_time();

		$response = wp_remote_post(
			'https://api.telegram.org/bot' . rawurlencode( $token ) . '/sendMessage',
			[
				'timeout' => 10,
				'headers' => [ 'Content-Type' => 'application/json' ],
				'body'    => wp_json_encode( [ 'chat_id' => $chat_id, 'text' => $full ] ),
			]
		);

		if ( is_wp_error( $response ) ) {
			// Transport failure (timeout, DNS, connection refused). Log internally so the
			// fire-and-forget callers that don't check the return value still leave a
			// trace the operator can grep. Without this, a Telegram outage is invisible.
			self::log_transport_failure( 'transport', CloudScale_Error_Text::in_seconds( $response->get_error_message() ) );
			return false;
		}

		$http_code = (int) wp_remote_retrieve_response_code( $response );
		if ( 200 !== $http_code ) {
			// Non-200 (401 bad token, 429 Telegram rate limit, etc.). Same reason as above.
			self::log_transport_failure( "HTTP {$http_code}", wp_remote_retrieve_body( $response ) );
			return false;
		}

		return true;
	}

	/**
	 * Logs a Telegram delivery failure so a silent outage or revoked bot token is
	 * discoverable. Deduplicated per-request so a burst of failed alerts doesn't flood
	 * the log.
	 *
	 * @param string $kind   Failure category (e.g. 'transport', 'HTTP 401').
	 * @param string $detail Error message or response body.
	 */
	private static function log_transport_failure( string $kind, string $detail ): void {
		static $logged = [];
		if ( isset( $logged[ $kind ] ) ) {
			return;
		}
		$logged[ $kind ] = true;

		$msg = 'CloudScale_Telegram: delivery failed (' . $kind . ')';
		if ( '' !== $detail ) {
			// Truncate: Telegram error bodies can be long, and the log is one line.
			$msg .= ': ' . substr( $detail, 0, 200 );
		}
		// phpcs:ignore WordPress.PHP.DevelopmentFunctions.error_log_error_log -- diagnostic trace for an alert channel that is itself down; no plugin-specific log is guaranteed to exist here
		error_log( $msg );
	}

	/**
	 * Save shared Telegram credentials from POST data.
	 * Call from a plugin's save AJAX handler after nonce verification.
	 */
	public static function save_from_post(): void {
		// phpcs:disable WordPress.Security.NonceVerification.Missing -- caller is responsible for nonce check
		self::opt_write( self::OPTION_TOKEN, self::LEGACY_TOKEN, sanitize_text_field( wp_unslash( $_POST['telegram_token'] ?? '' ) ) );
		self::opt_write( self::OPTION_CHAT_ID, self::LEGACY_CHAT_ID, sanitize_text_field( wp_unslash( $_POST['telegram_chat_id'] ?? '' ) ) );
		// phpcs:enable WordPress.Security.NonceVerification.Missing
	}

	/**
	 * Register the shared AJAX handlers (test + fetch-chat-id).
	 * Safe to call from multiple plugins; handlers are registered only once.
	 */
	public static function register_ajax(): void {
		if ( ! has_action( 'wp_ajax_cloudscale_telegram_fetch_chat_id' ) ) {
			add_action( 'wp_ajax_cloudscale_telegram_fetch_chat_id', static function (): void {
				if ( ! current_user_can( 'manage_options' ) ) {
					wp_send_json_error( 'Forbidden', 403 );
				}
				check_ajax_referer( 'cloudscale_telegram_fetch', 'nonce' );

				$token = sanitize_text_field( wp_unslash( $_POST['telegram_token'] ?? '' ) );
				if ( ! $token ) {
					wp_send_json_error( 'Bot token is required.' );
					return;
				}

				$response = wp_remote_get(
					'https://api.telegram.org/bot' . rawurlencode( $token ) . '/getUpdates',
					[ 'timeout' => 10 ]
				);

				if ( is_wp_error( $response ) ) {
					wp_send_json_error( 'Request failed: ' . CloudScale_Error_Text::in_seconds( $response->get_error_message() ) );
					return;
				}

				$code = (int) wp_remote_retrieve_response_code( $response );
				$body = wp_remote_retrieve_body( $response );
				$data = json_decode( $body, true );

				if ( $code !== 200 || empty( $data['ok'] ) ) {
					$detail = is_array( $data ) ? ( $data['description'] ?? $body ) : $body;
					wp_send_json_error( "Telegram HTTP {$code}: {$detail}" );
					return;
				}

				if ( empty( $data['result'] ) ) {
					wp_send_json_error( 'No messages yet. Send any message to your bot on Telegram first, then try again.' );
					return;
				}

				$chat_id = null;
				foreach ( $data['result'] as $update ) {
					$chat_id = $update['message']['chat']['id']
						?? $update['channel_post']['chat']['id']
						?? $update['my_chat_member']['chat']['id']
						?? null;
					if ( $chat_id !== null ) {
						break;
					}
				}

				if ( $chat_id === null ) {
					wp_send_json_error( 'Could not find a chat ID in the updates.' );
					return;
				}

				wp_send_json_success( [ 'chat_id' => (string) $chat_id ] );
			} );
		}

		if ( has_action( 'wp_ajax_cloudscale_telegram_test' ) ) {
			return;
		}
		add_action( 'wp_ajax_cloudscale_telegram_test', static function (): void {
			if ( ! current_user_can( 'manage_options' ) ) {
				wp_send_json_error( 'Forbidden', 403 );
			}
			check_ajax_referer( 'cloudscale_telegram_test', 'nonce' );

			// phpcs:disable WordPress.Security.NonceVerification.Missing -- nonce verified above
			$token   = sanitize_text_field( wp_unslash( $_POST['telegram_token'] ?? '' ) );
			$chat_id = sanitize_text_field( wp_unslash( $_POST['telegram_chat_id'] ?? '' ) );
			$source  = sanitize_text_field( wp_unslash( $_POST['test_source'] ?? '' ) ) ?: 'Telegram';
			// phpcs:enable WordPress.Security.NonceVerification.Missing

			// Fall back to stored credentials (used by the credentials panel test button).
			if ( ! $token ) { $token   = (string) self::opt_read( self::OPTION_TOKEN, self::LEGACY_TOKEN, '' ); }
			if ( ! $chat_id ) { $chat_id = (string) self::opt_read( self::OPTION_CHAT_ID, self::LEGACY_CHAT_ID, '' ); }

			if ( ! $token || ! $chat_id ) {
				wp_send_json_error( 'Bot token and chat ID are required.' );
				return;
			}

			$prefix   = self::alert_prefix( $source, 'info' );
			$response = wp_remote_post(
				'https://api.telegram.org/bot' . rawurlencode( $token ) . '/sendMessage',
				[
					'timeout' => 10,
					'headers' => [ 'Content-Type' => 'application/json' ],
					'body'    => wp_json_encode( [ 'chat_id' => $chat_id, 'text' => $prefix . 'Test message sent successfully. Alerts are working.' ] ),
				]
			);

			if ( is_wp_error( $response ) ) {
				wp_send_json_error( 'Telegram request failed: ' . CloudScale_Error_Text::in_seconds( $response->get_error_message() ) );
				return;
			}

			$code = (int) wp_remote_retrieve_response_code( $response );
			if ( $code !== 200 ) {
				$body    = wp_remote_retrieve_body( $response );
				$decoded = json_decode( $body, true );
				$detail  = is_array( $decoded ) ? ( $decoded['description'] ?? $body ) : $body;
				wp_send_json_error( "Telegram HTTP {$code}: {$detail}" );
				return;
			}

			wp_send_json_success( [ 'msg' => 'Test message sent.' ] );
		} );
	}

	/**
	 * Render the Telegram settings card.
	 *
	 * @param string $text_domain  Unused; kept for call-site compatibility across plugins.
	 */
	public static function render_settings_fields( string $text_domain, string $source = '' ): void {
		static $js_output = false;

		$token       = esc_attr( (string) self::opt_read( self::OPTION_TOKEN, self::LEGACY_TOKEN, '' ) );
		$chat_id     = esc_attr( (string) self::opt_read( self::OPTION_CHAT_ID, self::LEGACY_CHAT_ID, '' ) );
		$test_nonce  = wp_create_nonce( 'cloudscale_telegram_test' );
		$fetch_nonce = wp_create_nonce( 'cloudscale_telegram_fetch' );
		?>
		<div style="border-radius:8px;overflow:hidden;border:1px solid #b3e5fc;">
			<div style="background:linear-gradient(135deg,#0277bd 0%,#039be5 100%);padding:8px 14px;display:flex;align-items:center;gap:8px;">
				<span style="font-size:1rem;">&#9992;</span>
				<span style="color:#fff;font-weight:700;font-size:0.9rem;"><?php echo esc_html( 'Telegram' ); ?></span>
			</div>
			<div style="padding:14px;background:#f0f9ff;">
				<p class="cs-help"><?php echo esc_html( 'Instant push to your phone. Create a bot via @BotFather on Telegram, then paste the token and your chat ID below.' ); ?></p>
				<div style="margin-bottom:6px;">
					<label class="cs-field-label" style="display:block;margin-bottom:3px;"><?php echo esc_html( 'Bot Token' ); ?></label>
					<div style="display:flex;align-items:center;gap:8px;flex-wrap:wrap;">
						<input type="password" id="cs-telegram-token"
						       value="<?php echo esc_attr( $token ); ?>"
						       placeholder="123456789:ABCdefGhI..."
						       autocomplete="off" style="width:100%;max-width:300px;padding:4px 8px;height:32px;">
						<button type="button" id="cs-telegram-token-toggle" class="button" style="height:32px;padding:0 10px;font-size:0.82rem;">
							<?php echo esc_html( 'Show' ); ?>
						</button>
					</div>
				</div>
				<div style="margin-bottom:10px;">
					<label class="cs-field-label" style="display:block;margin-bottom:3px;"><?php echo esc_html( 'Chat ID' ); ?></label>
					<div style="display:flex;align-items:center;gap:8px;flex-wrap:wrap;">
						<input type="password" id="cs-telegram-chat-id"
						       value="<?php echo esc_attr( $chat_id ); ?>"
						       placeholder="-1001234567890"
						       autocomplete="off" style="width:150px;padding:4px 8px;height:32px;">
						<button type="button" id="cs-telegram-chat-toggle" class="button" style="height:32px;padding:0 10px;font-size:0.82rem;">
							<?php echo esc_html( 'Show' ); ?>
						</button>
						<button type="button" id="cs-telegram-fetch-btn" class="button"
						        data-nonce="<?php echo esc_attr( $fetch_nonce ); ?>">
							<?php echo esc_html( 'Fetch Chat ID' ); ?>
						</button>
					</div>
					<span id="cs-telegram-fetch-msg" style="font-size:0.88rem;display:block;margin-top:4px;"></span>
					<p class="cs-help" style="margin-top:4px;"><?php echo esc_html( 'Send any message to your bot on Telegram, then click Fetch Chat ID to auto-fill this field.' ); ?></p>
				</div>
				<div style="display:flex;align-items:center;gap:8px;">
					<button type="button" id="cs-telegram-test-btn" class="button"
					        data-nonce="<?php echo esc_attr( $test_nonce ); ?>"
					        data-source="<?php echo esc_attr( $source ); ?>">
						<?php echo esc_html( 'Send Test' ); ?>
					</button>
					<span id="cs-telegram-test-msg" style="font-size:0.88rem;"></span>
				</div>
			</div>
		</div>
		<?php if ( ! $js_output ) {
			$js_output = true;
			$telegram_settings_js =
				"(function(){\n"
				. "\t['cs-telegram-token','cs-telegram-chat-id'].forEach(function(inputId){\n"
				. "\t\tvar toggleId=inputId==='cs-telegram-token'?'cs-telegram-token-toggle':'cs-telegram-chat-toggle';\n"
				. "\t\tvar inp=document.getElementById(inputId);\n"
				. "\t\tvar btn=document.getElementById(toggleId);\n"
				. "\t\tif(!inp||!btn)return;\n"
				. "\t\tbtn.addEventListener('click',function(){\n"
				. "\t\t\tvar shown=inp.type==='text';\n"
				. "\t\t\tinp.type=shown?'password':'text';\n"
				. "\t\t\tbtn.textContent=shown?'Show':'Hide';\n"
				. "\t\t});\n"
				. "\t});\n"
				. "\tvar fetchBtn=document.getElementById('cs-telegram-fetch-btn');\n"
				. "\tif(fetchBtn){\n"
				. "\t\tfetchBtn.addEventListener('click',function(){\n"
				. "\t\t\tvar btn=this;\n"
				. "\t\t\tvar token=(document.getElementById('cs-telegram-token').value||'').trim();\n"
				. "\t\t\tvar msg=document.getElementById('cs-telegram-fetch-msg');\n"
				. "\t\t\tvar chatIn=document.getElementById('cs-telegram-chat-id');\n"
				. "\t\t\tif(!token){msg.textContent='Enter bot token first.';msg.style.color='#c00';return;}\n"
				. "\t\t\tbtn.disabled=true;\n"
				. "\t\t\tmsg.textContent='Fetching...';msg.style.color='#666';\n"
				. "\t\t\tvar fd=new FormData();\n"
				. "\t\t\tfd.append('action','cloudscale_telegram_fetch_chat_id');\n"
				. "\t\t\tfd.append('nonce',btn.dataset.nonce);\n"
				. "\t\t\tfd.append('telegram_token',token);\n"
				. "\t\t\tfetch(ajaxurl,{method:'POST',body:fd})\n"
				. "\t\t\t\t.then(function(r){return r.json();})\n"
				. "\t\t\t\t.then(function(d){\n"
				. "\t\t\t\t\tif(d.success){chatIn.value=d.data.chat_id;msg.textContent='Chat ID found: '+d.data.chat_id;msg.style.color='#0a5';}\n"
				. "\t\t\t\t\telse{msg.textContent=d.data||'Failed.';msg.style.color='#c00';}\n"
				. "\t\t\t\t})\n"
				. "\t\t\t\t.catch(function(){msg.textContent='Request error.';msg.style.color='#c00';})\n"
				. "\t\t\t\t.finally(function(){btn.disabled=false;});\n"
				. "\t\t});\n"
				. "\t}\n"
				. "\tvar testBtn=document.getElementById('cs-telegram-test-btn');\n"
				. "\tif(testBtn){\n"
				. "\t\ttestBtn.addEventListener('click',function(){\n"
				. "\t\t\tvar btn=this;\n"
				. "\t\t\tvar msg=document.getElementById('cs-telegram-test-msg');\n"
				. "\t\t\tbtn.disabled=true;\n"
				. "\t\t\tif(msg){msg.textContent='Sending...';msg.style.color='#666';}\n"
				. "\t\t\tvar fd=new FormData();\n"
				. "\t\t\tfd.append('action','cloudscale_telegram_test');\n"
				. "\t\t\tfd.append('nonce',btn.dataset.nonce);\n"
				. "\t\t\tfd.append('test_source',btn.dataset.source||'');\n"
				. "\t\t\tfetch(ajaxurl,{method:'POST',body:fd})\n"
				. "\t\t\t\t.then(function(r){return r.json();})\n"
				. "\t\t\t\t.then(function(d){\n"
				. "\t\t\t\t\tif(msg){msg.textContent=d.success?(d.data&&d.data.msg?d.data.msg:'Sent.'):(d.data||'Failed.');msg.style.color=d.success?'#0a5':'#c00';}\n"
				. "\t\t\t\t})\n"
				. "\t\t\t\t.catch(function(){if(msg){msg.textContent='Request error.';msg.style.color='#c00';}})\n"
				. "\t\t\t\t.finally(function(){btn.disabled=false;});\n"
				. "\t\t});\n"
				. "\t}\n"
				. "})();\n";
			// phpcs:ignore WordPress.WP.EnqueuedResourceParameters.NoExplicitVersion -- virtual inline-only handle, no src URL, no cache-busting needed
			wp_register_script( 'cloudscale-telegram-ui', false, array(), false, true );
			wp_add_inline_script( 'cloudscale-telegram-ui', $telegram_settings_js );
			if ( ! wp_script_is( 'cloudscale-telegram-ui', 'enqueued' ) ) {
				wp_enqueue_script( 'cloudscale-telegram-ui' );
			}
		}
	}
}
